version: '3.8'

services:
  fauxx:
    image: steimerbyte/fauxx:latest
    container_name: fauxx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  data:
