services:
  fauxx:
    image: steimerbyte/fauxx:latest
    container_name: fauxx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /home/docker/fauxx/data:/data
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
