from enum import Enum


class ActionType(str, Enum):
    SEARCH_QUERY = "SEARCH_QUERY"
    AD_CLICK = "AD_CLICK"
    PAGE_VISIT = "PAGE_VISIT"
    LOCATION_SPOOF = "LOCATION_SPOOF"
    DNS_LOOKUP = "DNS_LOOKUP"
    COOKIE_HARVEST = "COOKIE_HARVEST"
    DEEP_LINK_VISIT = "DEEP_LINK_VISIT"
    FINGERPRINT_ROTATE = "FINGERPRINT_ROTATE"
    AD_PROFILE_IMPORT = "AD_PROFILE_IMPORT"


class CategoryPool(str, Enum):
    MEDICAL = "MEDICAL"
    LEGAL = "LEGAL"
    AUTOMOTIVE = "AUTOMOTIVE"
    PARENTING = "PARENTING"
    RETIREMENT = "RETIREMENT"
    GAMING = "GAMING"
    AGRICULTURE = "AGRICULTURE"
    FASHION = "FASHION"
    ACADEMIC = "ACADEMIC"
    REAL_ESTATE = "REAL_ESTATE"
    COOKING = "COOKING"
    SPORTS = "SPORTS"
    FINANCE = "FINANCE"
    TRAVEL = "TRAVEL"
    TECHNOLOGY = "TECHNOLOGY"
    PETS = "PETS"
    HOME_IMPROVEMENT = "HOME_IMPROVEMENT"
    BEAUTY = "BEAUTY"
    MUSIC = "MUSIC"
    FITNESS = "FITNESS"
    ENTERTAINMENT = "ENTERTAINMENT"
    FOOD = "FOOD"
    POLITICS = "POLITICS"
    SCIENCE = "SCIENCE"
    BUSINESS = "BUSINESS"
    OUTDOOR_RECREATION = "OUTDOOR_RECREATION"
    CRAFTS = "CRAFTS"
    HISTORY = "HISTORY"
    ENVIRONMENT = "ENVIRONMENT"
    MILITARY_DEFENSE = "MILITARY_DEFENSE"
    WELLNESS_ALTERNATIVE = "WELLNESS_ALTERNATIVE"
    RELATIONSHIPS_DATING = "RELATIONSHIPS_DATING"


class IntensityLevel(str, Enum):
    LOW = "LOW"      # 12/hr
    MEDIUM = "MEDIUM"  # 60/hr
    HIGH = "HIGH"    # 200/hr

    @property
    def actions_per_hour(self) -> int:
        return {
            IntensityLevel.LOW: 12,
            IntensityLevel.MEDIUM: 60,
            IntensityLevel.HIGH: 200,
        }[self]
